#----服务器------------------------------------------------------------------------------------------------------------#
server:
  port: 14702

#----Spring------------------------------------------------------------------------------------------------------------#
spring:
  #----数据源连接方式---------------------------------------------------------------------------------------------------#
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
#----数据源------------------------------------------------------------------------------------------------------------#
datasource:
  #主数据源
  primary:
    url: jdbc:mysql://127.0.0.1:3306/b_company?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: boodoou
    password: boodoou
  #次数据源
  secondary:
    url: jdbc:mysql://127.0.0.1:3306/b_account?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: boodoou
    password: boodoou